# Generated by Django 4.1.5 on 2023-01-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
