# Generated by Django 4.1.5 on 2023-01-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_entry_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='img',
            field=models.ImageField(blank=True, default='default_emp_male.png', null=True, upload_to='emp_images/'),
        ),
    ]
