# Generated by Django 4.1.5 on 2023-01-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_employee_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='img',
            field=models.ImageField(default='default_emp_male.png', upload_to='emp_images'),
        ),
    ]
