# Generated by Django 4.1.5 on 2023-01-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_employee_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='img',
            field=models.ImageField(default='default_section.png', upload_to='section_images'),
        ),
    ]
