# Generated by Django 4.1.5 on 2023-01-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_section_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='img',
            field=models.ImageField(default='default_emp.png', upload_to='emp_images'),
        ),
    ]
