# Generated by Django 4.1.5 on 2023-01-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_employee_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='img',
            field=models.ImageField(default='default_emp.jpg', upload_to='emp_images'),
        ),
    ]
