# Generated by Django 4.1.5 on 2023-01-09 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_alter_entry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_work',
            name='_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.employee'),
        ),
        migrations.AlterField(
            model_name='employee_work',
            name='_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.work'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.employee'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.section'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.work'),
        ),
        migrations.AlterField(
            model_name='section_work',
            name='_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.section'),
        ),
        migrations.AlterField(
            model_name='section_work',
            name='_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.work'),
        ),
    ]
